### PR TITLE
Upload built docs as an artifact to ease human review.

### PR DESCRIPTION
**Pull request by fnordahl**
Closes-Bug: #2043076

A example of a successful run can be viewed in https://github.com/fnordahl/microovn/actions/runs/6811649912

### CODE REVIEW

**Comment by fnordahl** [comment]
> What is the use case for this? Usually, the docs are also built by the readthedocs action run, and there they will also be hosted (which is a lot easier to consume).

That does indeed sound like an even better option, I was unaware of there being a separate readthedocs action run. Where do I find it and/or its output, should this be documented in the shared workflow file for future travelers?

> I'm not opposed to getting this in, but for more extensive documentation sets, the artefact will be quite big, which might increase the run time of the action. And not sure if we have any limit on stored artefacts?
> 
> Maybe we could have this in a separate job, so every team can choose whether they want to run this?

The main reason for proposing it here is to conserve resources and not do the same build multiple times. Depending on the outcome of the conversation above I can see if we can make it configurable and default to off.

**Comment by pmatulis** [comment]
The MicroOVN RTD configuration was missing something, which has been corrected. However, as a test, MicroOVN PR [#94](https://github.com/canonical/microovn/pull/94) is still not showing what we want after re-running the Doc job. This is what is expected, from a MicroCeph PR:

image

The Details button is a link to the rendered RTD build.

**Comment by ru-fu** [comment]
> That does indeed sound like an even better option, I was unaware of there being a separate readthedocs action run. Where do I find it and/or its output, should this be documented in the shared workflow file for future travelers?

This is documented here in the library: https://library.canonical.com/documentation/publish-on-read-the-docs#enable-pr-previews-9
It's not related to the workflows, but it's a feature of RTD, so I think it would be out of place to document it here.

It *should* work out of the box after enabling the pull request previews. If it doesn't, try resyncing the webhook: https://docs.readthedocs.io/en/stable/guides/pull-requests.html#troubleshooting

**Comment by fnordahl** [comment]
> > That does indeed sound like an even better option, I was unaware of there being a separate readthedocs action run. Where do I find it and/or its output, should this be documented in the shared workflow file for future travelers?
> 
> This is documented here in the library: https://library.canonical.com/documentation/publish-on-read-the-docs#enable-pr-previews-9 It's not related to the workflows, but it's a feature of RTD, so I think it would be out of place to document it here.
> 
> It _should_ work out of the box after enabling the pull request previews. If it doesn't, try resyncing the webhook: https://docs.readthedocs.io/en/stable/guides/pull-requests.html#troubleshooting Note that this must be done by someone who has write access to the GitHub repo.

Thanks a lot for the links, I was unaware of this documentation.

PS: If I click the [result for the RTD build](https://readthedocs.com/projects/canonical-microovn/builds/1837789/) I get a 403, as would any of our contributors. Would it be possible to make the build logs public?

**Comment by ru-fu** [comment]
> PS: If I click the [result for the RTD build](https://readthedocs.com/projects/canonical-microovn/builds/1837789/) I get a 403, as would any of our contributors. Would it be possible to make the build logs public?

Yes, it's the "Privacy level" setting here:
image

**Comment by pmatulis** [comment]
I made a change, a different one though.

**Pull request closed without merging**
